// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 6/27/2024, 11:20:17 AM
const configMerger = require("/Users/vittoraguiar/Documents/Projetos/Pessoais/nuxt-essential/node_modules/@nuxtjs/tailwindcss/dist/runtime/merger.mjs");

const inlineConfig = {"content":[],"theme":{"extend":{}},"plugins":[]};

const config = [

].reduce((prev, curr) => configMerger(curr, prev), configMerger(inlineConfig, { content: ["/Users/vittoraguiar/Documents/Projetos/Pessoais/nuxt-essential/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/vittoraguiar/Documents/Projetos/Pessoais/nuxt-essential/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/vittoraguiar/Documents/Projetos/Pessoais/nuxt-essential/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/vittoraguiar/Documents/Projetos/Pessoais/nuxt-essential/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/vittoraguiar/Documents/Projetos/Pessoais/nuxt-essential/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/vittoraguiar/Documents/Projetos/Pessoais/nuxt-essential/plugins/**/*.{js,ts,mjs}","/Users/vittoraguiar/Documents/Projetos/Pessoais/nuxt-essential/composables/**/*.{js,ts,mjs}","/Users/vittoraguiar/Documents/Projetos/Pessoais/nuxt-essential/utils/**/*.{js,ts,mjs}","/Users/vittoraguiar/Documents/Projetos/Pessoais/nuxt-essential/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/vittoraguiar/Documents/Projetos/Pessoais/nuxt-essential/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/vittoraguiar/Documents/Projetos/Pessoais/nuxt-essential/app.config.{js,ts,mjs}"] }));

module.exports = config
